### ISSUE TITLE
Rename repos

### ISSUE THREAD

**Issue by mabelzhang** [osrf/mbari_wec#34]
Rename
- [x] buoy_entrypoint to mbari_wec
- [x] buoy_sim to mbari_wec_gz ~~mbariwec_sim / mbariwec_simulator (long name) / mbariwec_gz (to avoid name clash with the other DoE WEC Sim project)~~
- [x] buoy_msgs to ~~mbariwec_interfaces / mbariwec_api / mbari_wec_comms /~~ mbari_wec_utils
  - Suffixes for reference: msgs, interfaces, comms, common, utils, support, module, suite, extensions
  - [ ] Rename both the repo and the meta-package currently called buoy_sim, and remove buoy_msgs from buoy_gazebo package.xml

Followup:
- [ ] Currently, README and other documentation refer to "Buoy Sim" as the project name, corresponding to the old repo name `buoy_sim`. Since we've now changed that repo name to `mbari_wec_gz`, "Buoy Sim" doesn't correspond to anything anymore and could confuse readers. What do we want to call the project? To be explicit and avoid name clashing with "WEC Sim", maybe "MBARI WEC Gz Simulation" for the first time in a document, and subsequent occurrences a shorter "WEC Gz Sim"? Original comment https://github.com/osrf/mbari_wec/pull/38#discussion_r1148867986

**Comment by quarkytale** [comment]
Maintaining consistency with the template repos, might `mbari_wec` work better than `mbariwec`?

**Comment by andermi** [comment]
I just worry about conflict with WEC-SIM if we separate mbari and wec

**Comment by mabelzhang** [comment]
I can see mbari_wec being easier to read and remember than mbariwec though, if you're advertising this repo to an audience in a presentation. MBARI and WEC are technically two words, and squishing them together makes a longer word that someone new to MBARI or WEC might find harder to type correctly quickly.

I guess it depends on which one is more important or more likely to cause trouble. Do you want to prioritize a name easy for new users to find, or would the name clash be very confusing for many people.

@tfoote naming suggestions?

**Comment by mabelzhang** [comment]
Updating from meeting:
Group agrees on `mbari_wec`
Use `mbari_wec_gz` for `buoy_sim` to avoid clashing with WEC-SIM

What:
Only repo name (probably only need to change buoy_entrypoint high-level files), not package names

When:
Before releasing Docker

**Comment by quarkytale** [comment]
Updated project name from Buoy Sim to MBARI WEC in https://github.com/osrf/mbari_wec/pull/44
